[workspace]
members = [
    "src/openwhoop-codec",
    "src/openwhoop-migration",
    "src/openwhoop-entities",
    "src/openwhoop",
    "src/openwhoop-algos",
    "src/openwhoop-types",
    "src/openwhoop-db",
]
resolver = "3"