[package]
name = "openwhoop-algos"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
openwhoop-codec.workspace = true
openwhoop-types.workspace = true

[dev-dependencies]
rand.workspace = true
