[package]
name = "openwhoop-codec"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.11"
uuid = "1.11.1"
